default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aries_development
  username: aries_user
  password: lobus5310

test:
  <<: *default
  database: aries_test
  username: aries_user
  password: lobus5310

production:
  <<: *default
  database: aries_production
  username: aries_user
  password: lobus5310
